import random
prices = list(range(51))
notes_of_100 = 0
notes_of_50 = 0
notes_of_20 = 0
notes_of_10 = 0
coins_of_5 = 0
coins_of_2 = 0
coins_of_1 = 0
cost = random.choice(prices)
amount = int(input("Enter Your Amount : "))
final_amount = amount - cost
print("Change = ",final_amount)
if (final_amount >= 100):
    notes_of_100 = final_amount // 100
    final_amount -= notes_of_100 * 100
if (final_amount >= 50):
    notes_of_50 = final_amount // 50
    final_amount -= notes_of_50 * 50
if (final_amount >= 20):
    notes_of_20 = final_amount // 20
    final_amount -= notes_of_20 * 20
if (final_amount >= 10):
    notes_of_10 = final_amount // 10
    final_amount -= notes_of_10 * 10
if (final_amount >= 5):
    coins_of_5 = final_amount // 5
    final_amount -= coins_of_5 * 5
if (final_amount >= 2):
    coins_of_2 = final_amount // 2
    final_amount -= coins_of_2 * 2
if (final_amount >= 1):
    coins_of_1 = final_amount // 1
print("Notes of 100 = ",notes_of_100)
print("Notes of 50 = ",notes_of_50)
print("Notes of 20 = ",notes_of_20)
print("Notes of 10 = ",notes_of_10)
print("Coins of 5 = ",coins_of_5)
print("Coins of 2 = ",coins_of_2)
print("Coins of 1 = ",coins_of_1)